### ISSUE TITLE
Darkmode Change tab text color

### ISSUE THREAD

**Issue by Melleh98** [pyrevitlabs/pyRevit#2143]
## R24 Darkmode tab text color

I just updated my toolbars to show white icons when using R24 dark mode. It works great.
![image](https://github.com/eirannejad/pyRevit/assets/154245746/fab889db-7ada-427f-bd06-126404ad7d05)
![image](https://github.com/eirannejad/pyRevit/assets/154245746/92f41f18-542d-4d25-9695-4b5d325fedb9)
I also color coördinate my tabs so its easier to look for things.
In darkmode tho the text is almost unreadable.

## Ideal solutuion

The best solution for me would be to add a way to edit the text color of the tabs

## Alternative solution

An alternatve could be:
Being able to set a different tab color for Darkmode just like we can use PNG's just for the  dark mode Icon

**Comment by jmcouffin** [comment]
@dosymep 
Could you take a look at that?

**Comment by dosymep** [comment]
@Melleh98, maybe you can choose colour wich same for two modes?

```yml

background:
  title: '#31363F'

```

@jmcouffin, maybe add dark properties?

```yml

# set background dark for all parts
background-dark: '#ff0000' 

# or for individual dark parts
background-dark:
  panel: '#ff0000'
  title: '#00ff00'
  slideout: '#0000ff'

```

**Comment by jmcouffin** [comment]
> @jmcouffin, maybe add dark properties?

That would make sense @dosymep 
Would you mind taking care of that?

**Comment by jmcouffin** [comment]
@Melleh98 
following Dosymep suggestion you can set color to a middle ground color that works in both cases

https://www.notion.so/pyrevitlabs/pyRevit-Bundles-12323e3090904d9aa7cdc3d82095d3e3?pvs=4#225b2cf0dad24b0395de1930f1070ad6

```
# set background for all parts
background: '#ff0000'                   # or ARGB e.g. #ff0000ff

# or for individual parts
background:
  panel: '#ff0000'
  title: '#00ff00'
  slideout: '#0000ff'
```
