### ISSUE TITLE
[RFC] Switch to manifest-based extensions instead of folder-based extensions

### ISSUE THREAD

**Issue by sanzoghenzo** [pyrevitlabs/pyRevit#2648]
## Is your feature request related to a problem? Please describe

The current extensions bundles discovery can be easy for newcomers, but when your extension grows, it can be a PITA to handle.

The main reason is that IDEs, that are made to work with standard python projects, don't play well with the current folder structures. You got a bunch of squiggles because IDEs don't know that you have to add the buttons and lib folders in `sys.path`.

Also, having a lot of `script.py` tabs open can be a great source of confusion!

## Describe the solution you'd like

I believe that we could benefit from a single yaml manifest that declares the extension properties and all its components (tabs, panels, and so on) instead of using directories and fixed file naming to discover the scripts.

- The discovery service just reads the yaml file and the files declared in them (we could use the python entrypoint way such as package.module[:function] and extend it to the other languages), that should result in faster loading time
- The code could be arranged like a normal python package, so that IDEs and other python tools are happy

Basically, the current bundle.yaml files will be consolidated into a single one, and will have a new field that is the script path as explained above.
We could create a tool to migrate the existing extensions and make the transition less painful.

Also, when we finally can transition to CPython with the patched python.net, we could leverage a `dependencies` attribute to directly download the dependencies from pypi (and ideally create isolated environments with `uv`, so that there's no conflict with the base pyRevit library and other extensions)

## Additional context

This is a very rough schema that collects the info of the various bundle types (at least what I understood reading the documentations and some code, I might have missed something/a lot of things).

<details><summary>Manifest example</summary>
<p>
```yaml
kind: Extension # this is borrowed from kubernetes, we can drop that
name: My extension
dependencies: []
commands:  # the current nobutton
  - name: my hidden command
templates:
  long_string: a very long text to reuse
tabs:
  - name: My Tab
    highlight_type: new/updated
    panels:
      - name: My panel
        collapsed: false
        is_beta: false
        background:
          panel: #FFFFFF
          title: #CCCCCC
          slideout: #AAAAAA
        highlight: new/update
        layout:
          - type: stack
            name: first stack
            components: # max 3 items
              - ...
          - type: pushbutton
            title: my button # can be multilingual
            icon: xxx.png
            entrypoint: package.mymodulename # we could also add :myfunction
            media_file: ...
            help_url: ...
            avail_class_name: ...
            highlight: new/update
            authors:
              - ...
            context: # zero-doc, selection, categories, any, all, exact, ....
              - ...
            is_beta: false
            min_revit_version: 2015
            max_revit_version: 2024
          - type: content
            title: my content
            contents:
              - .....rfa
            optional_contents:
              - .....rfa
            icon: xxx.png
            tooltip:
               image: xxx.png
               video: yyy.mp4
          - type: urlbutton
            title: my url
            hyperlink: http://exmaple.com
            icon: xxx.png
            tooltip:
              image: xxx.png
              video: xxx.mp4
          - type: separator
          - type: pulldown
            title: my pulldown
            icon: xxx.png
            components:
              - ...
          - type: splitbutton
            title: my splitbutton
            icon: xxx.png
            components:
              - ...
          - type: splitpushbutton
            title: my split push button
            icon: xxx.png
            components:
              - ...
          - type: smartbutton
            title: my smart button
            icon: xxx.png
          - type: invokebutton
            title: my invoke button
            icon: xxx.png
            assembly: Test.dll
            command_class: MyClass
          - type: linkbutton
            title: my link button
            icon: xxx.png
            assembly: LinkTest.dll
            command_class: TextClass
            availability_class: TextAvailability
        slideout:
          - # item in the slide-out panel
        panelbutton: # At this point I was lost/bored, I don't even know what a panel button is!
```
</p>

Feel free to share your thoughts!
</details>
